env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 'latest'
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {}
