env:
  browser: true
  es2021: true
  node: true
overrides:
  - files: ['*.ts', '*.tsx']
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaFeatures:
        jsx: true
      ecmaVersion: latest
      sourceType: module
    extends:
      - plugin:react/recommended
      - plugin:react/jsx-runtime
      - plugin:react-hooks/recommended
      - plugin:jsx-a11y/recommended
      - prettier
    plugins:
      - react
      - prettier
      - '@typescript-eslint'
    rules:
      prettier/prettier: warn
      arrow-body-style: off
      prefer-arrow-callback: off
    settings:
      react:
        version: detect
